name: openmc-dash-interface
channels:
    - conda-forge
dependencies:
- python=3.6
- anaconda
- anaconda-client
- conda
- openmc
- pip
- pip:
  - dash
  - plotly
  - dash-core-components
  - dash-html-components
  - dash-daq
  - numpy
  - pandas
  - gunicorn
